# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
       
     # Instalar dependencias
    - name: Install dependencies
      run: node -v && pnpm install

      # Construir el proyecto
    - name: Build the project
      run: pnpm run build

    - name: Permision Accept 
      run: sudo chmod 777 /home/intisoft/htdocs/intisoft.com.pe/actions-runner/_work/intisoft-frontend/intisoft-frontend/dist
